const EndPoints = {
    login: "api/v1/login/",
    admindashboard: "api/v1/admin/dashboard/",
    adminadduser: "api/v1/admin/user/",
    adminuser: "api/v1/admin/user/",
    adminedituser: "api/v1/admin/user/",
    admindeleteuser: "api/v1/admin/user/",
    ingedients: "api/v1/admin/ingredient/",
    recipe: "api/v1/admin/recipe/",
    store: "api/v1/admin/store/",
    state: "api/v1/admin/state/",
    tag: "api/v1/admin/tag",
    notification: "api/v1/admin/notification",
    subscription: "api/v1/stripe/subscriptionPlan",
    subscriptions: "api/v1/admin/stripe/subscription/",
    recipeIngredient: "api/v1/admin/recipeIngredient/",
    recipeSide: "api/v1/admin/recipeSide/",
    uploadContent: "api/v1/admin/uploadContent/",
    ingedientsCategory: "api/v1/admin/ingredientCategory/",
    shoppingCategory: "api/v1/admin/shoppingCategory/",
    ingredientMeausurment: "api/v1/admin/ingredientMeasurement/",
    bonusContent: "api/v1/bonusContent/",
    adminBonusContent: "api/v1/admin/bonusContent/",
    uploadSpecial: "api/v1/admin/uploadSpecial/",
    getSpecial: "api/v1/admin/store/{id}/special/",
    resetPassword: "api/v1/resetPassword/",
    forgotPassword: "api/v1/forgotPassword/",
};

export default EndPoints;
