insert into thedinne_backend.states (name, abbr, created, updated) values ('Alabama', 'AL', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Alaska', 'AK', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('American Samoa', 'AS', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Arizona', 'AZ', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Arkansas', 'AR', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('California', 'CA', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Colorado', 'CO', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Connecticut', 'CT', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Delaware', 'DE', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('District of Columbia', 'DC', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Federated of Micronesia', 'FM', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Florida', 'FL', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Georgia', 'GA', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Guam', 'GU', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Hawaii', 'HI', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Idaho', 'ID', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Illinois', 'IL', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Indiana', 'IN', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Iowa', 'IA', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Kansas', 'KS', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Kentucky', 'KY', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Louisiana', 'LA', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Maine', 'ME', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Marshall Islands', 'MH', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Maryland', 'MD', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Massachusetts', 'MA', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Michigan', 'MI', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Minnesota', 'MN', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Mississippi', 'MS', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Missouri', 'MO', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Montana', 'MT', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Nebraska', 'NE', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Nevada', 'NV', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('New Hampshire', 'NH', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('New Jersey', 'NJ', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('New Mexico', 'NM', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('New York', 'NY', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('North Carolina', 'NC', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('North Dakota', 'ND', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Northern Mariana Islands', 'MP', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Ohio', 'OH', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Oklahoma', 'OK', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Oregon', 'OR', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Palau', 'PW', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Pennsylvania', 'PA', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Puerto Rico', 'PR', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Rhode Island', 'RI', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('South Carolina', 'SC', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('South Dakota', 'SD', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Tennessee', 'TN', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Texas', 'TX', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Utah', 'UT', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Vermont', 'VT', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Virgin Islands', 'VI', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Virginia', 'VA', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Washington', 'WA', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('West Virginia', 'WV', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Wisconsin', 'WI', now(), now());
insert into thedinne_backend.states (name, abbr, created, updated) values ('Wyoming', 'WY', now(), now());