const privacy_policy = `<p><strong>Updated as of December 31, 2019</strong></p>
<p>We respect your privacy and are committed to ensuring that it is protected. This Privacy Policy outlines how we use and protect any information that you share when you use our website and services, which we refer to in this Policy as the “Services”.</p>
<p>This Privacy Policy has been updated to provide Transparency, so you understand what information we collect and how we use it, and clarify your Rights and Control over this information.</p>
<p>This Privacy Policy applies only to information collected through our website and not to information collected offline, if any. By using our site, you consent to this Privacy Policy and to the collection and use of your information as we describe in this Policy.</p>
<p><strong>Information We Collect and How It Is Used</strong></p>
<p>When you connect to our website through your computer, phone or tablet, we may make use of Cookies, which are small text files that are sent to or accessed from your web browser or your computer’s hard drive. A cookie often includes the name of the domain (internet location) from which the cookie originated, the expiration date of the cookie and a&nbsp; unique number or similar identifier. A cookie also may contain information about your computer, such as user settings, browsing history and activities conducted while using the Services.</p>
<p>We use Cookies to:</p>
<ul>
<li>understand how you arrived to The Dinner Daily website and whether you clicked on another link to get there,</li>
<li>understand how you navigate through the website and whether you ultimately subscribe to The Dinner Daily,</li>
<li>allow you to stay signed in to The Dinner Daily for a specific time period without having to log in each visit, if you are a member.</li>
</ul>
<p>When you subscribe to the Services, we collect information from you that you provide, including your name, your email address and the state in which you live. For purposes of this Policy, we will call this information that we collect your “Personally Identifiable Information” (PII). We also collect user preferences regarding menu store and shopping options selected, and usage information such as which recipes are Favorited, switched to another recipe, changes made to shopping lists and so forth. This information is to enable us to better provide the Services to you (we will refer to this information as “User Preferences”). Any information that you submit to us is used by us to provide you with the Services, to provide important information about the Services and enhancements to the Services and to provide information about related Services from our partners.</p>
<p>Because your PII is essential for us to deliver the Services to you, it’s important that your PII be complete and accurate. By using the Services, you represent and warrant that all information you provide in connection with your use of the Services will be complete and accurate, and that you will update that information as necessary to maintain its completeness and accuracy.</p>
<p>Payment information provided by you, including your Credit Card Number, Expiration Date and CVC is collected by our payment processor, and is not stored on our servers. To view our payment processor’s privacy policies, please go to stripe.com. We have limited visibility of the Payment information you provide, specifically the name of the card holder, the last four digits of the credit card, the type of card and expiration date. We use this information solely for providing the service and do not share or sell it with any other party.</p>
<p><strong>How We May Disclose or Share the Information We Collect</strong></p>
<p><strong>Except as otherwise described in this Policy, we do not and will not share, sell, trade or rent your PII and User Preferences</strong>.&nbsp; If necessary to provide the Services, we may share PII and User Preferences with trusted third parties who assist us in operating our website, conducting our business, or providing Services. These parties only have access to the PII and User Preference data that they need to perform their respective services. More importantly, they are required to keep this information confidential and may not use it other than as we ask them to and always in accordance with this Privacy Policy.</p>
<p>In addition, if you signed up for service through a promotion with a third party, we may share your PII and User Preference data with that third party.&nbsp; The third party is required to keep this information confidential, and may not share it with other parties.&nbsp; The third party may use this information to send you marketing and other materials about its business.&nbsp; You should consult such third party’s privacy policy to understand more about how the third party may use your PII and User Preference data.</p>
<p>We may share your PII (but not your User Preferences) as follows:</p>
<ol>
<li>With your employer, if the Services are an employer-provided benefit, to verify you are an employee and eligible for the benefit.</li>
<li>With your health insurance company, if the Services are an employer-provided benefit sponsored by or through your health insurance company, to verify you are an insured and eligible for the benefit</li>
<li>To comply with the law, enforce our site policies, or protect ours or other’s rights, property, or safety, as part of the transfer of assets or property in connection with an acquisition or merger, or to the extent ordered by bankruptcy law.</li>
</ol>
<p>By using the Services, you consent to the sharing of your Personal Information and User Preferences as set forth above.&nbsp; If you do not consent to this, you should immediately stop using our service.</p>
<p>This website is intended for use by people over the age of eighteen (18). We do not knowingly collect PII from children. If we learn that we have collected PII from anyone under the age of eighteen (18) we will promptly destroy it. Please contact us using the contact information below if you believe that we have such information in our possession.</p>
<p><strong>Using Our Google Calendar Connection</strong></p>
<p>Users who opt to use “Send to Calendar” authorize the Services to add their menu items to their Google Calendar as dinner events. We do not share or store any user Google Calendar data on our system.</p>
<p><strong>Information Security and Retention</strong></p>
<p>The security of your PII is paramount. We have implemented and maintain a variety of security procedures and practices to maintain the security and safety of your information. We also ensure that members of our team are trained in protecting your information. However, because transmission via the internet is not completely secure, we cannot guarantee the security of your information collected through this website.</p>
<p>We retain your information only for as long as we need to, to be able to use it for the purposes listed in this Privacy Policy, and for as long as we are required to keep it by law.</p>
<p>If you live outside of the US, when you join The Dinner Daily, your PII is stored on computer servers in the US.</p>
<p><strong>Your Rights and Choices</strong></p>
<p>If you have received a mailing from us, our records indicate that you have either (1) requested information from us or (2) have an active subscription with us. If you believe you have received unwanted, unsolicited email sent from us, please contact us at&nbsp;<a href="mailto:info@thedinnerdaily.com">info@thedinnerdaily.com</a>, or simply unsubscribe from our mailings.</p>
<p>We may provide links to other websites which are not owned and operated by us. We have no control over and are not responsible for the content of those sites or how the third parties responsible for them collect and use your PII. Third party websites may have their own privacy polices explaining how they use and share your PII. You should carefully review those privacy policies before you use these websites to make sure that you are comfortable with how your PII is being collected and shared.</p>
<p>As previously noted, we may partner with third parties from time to time in marketing our services.&nbsp; If you sign up for our service through a third party, you should consult that third party’s privacy policy to understand more about how they may use your PII and User Preference data.&nbsp; We may also provide a link to the third party’s website.&nbsp; We are not responsible for the content on such websites, or any additional information that such websites may collect from you.</p>
<p><strong>Control Over Your Information</strong></p>
<p>If you would like us to delete your PII, or if you do not want us to (i) send you marketing materials other than our service, or (ii) share your PII and/or User Preference data with a third party marketing partner, please contact us at info@thedinnerdaily.com. We are happy to accommodate your request, but we may retain an archived copy of your information as required by law or for other legitimate business purposes.</p>
<p><strong>Updates to this Privacy Policy</strong></p>
<p>We may change our Privacy Policy from time to time without notice and update the effective date of this Privacy Policy accordingly. If we decide to change our Privacy Policy, we will post those changes on this page, so we encourage you to periodically review this Privacy Policy. If you continue using our website after we change our Privacy Policy, we will deem your continued use to mean that you have accepted the then-current terms of the Privacy Policy.</p>
<p>If you are located outside of the United States and choose to share your information with us, your information may be transferred, stored, and processed in the United States. By providing your information to us by way of our website, you consent to the collection, transfer, use, storage and disclosure of your information as disclosed in this Privacy Policy.</p>
<p><strong>Contact</strong></p>
<p>If you have any questions about this policy, or want to contact us, please do so at <a href="mailto:info@thedinnerdaily.com">info@thedinnerdaily.com</a>.</p>`

const term_condition =`<p>Updated as of 1-1-2020</p>
<p>By setting up a Dinner Daily account and using the Dinner Daily service, you agree to these terms and conditions:</p>
<p>The Dinner Daily is a dinner planning service (the “Service”) offering personalized dinner plans based on a subscriber’s food preferences and the weekly specials at major grocery stores. Each subscriber will receive a customized weekly menu and shopping list for five dinners delivered to the subscriber’s personal dashboard. Subscribers will also receive links to their weekly dinner plan via email.</p>
<ul>
<li>By signing up you are agreeing to be billed on a recurring basis in accordance with your subscription term. Six (6) month subscriptions will be billed every 6 months and Annual (12 months) subscriptions will be billed on the annual anniversary date.&nbsp; All subscriptions shall automatically renew until they are set to cancel by the subscriber in their Account Settings area of their account.</li>
<li>All subscriptions offer a 14 day trial.&nbsp; You will not be charged the subscription fee for the first 14 days of your membership. <strong>On day 15, unless cancelled within the first 14 days, you will be charged the subscription fee for the term you selected upon signing up for the service.&nbsp; Members can cancel through their Account Settings page on thedinnerdaily.com</strong></li>
<li>The Subscription is to be used by the Subscriber or Subscriber’s household only. &nbsp;The weekly menu or shopping list reports cannot be distributed, copied, or forwarded to another email address without permission from The Dinner Daily Inc.&nbsp; Sign in details for the site may not be shared beyond the subscriber’s household.&nbsp; Our&nbsp; system will send us an alert if multiple IP addresses are logging in with the same user ID and password. If this policy is violated, we reserve the right to cancel your account immediately.</li>
<li>Menu Plans are available to subscribers by logging into the Member’s Dashboard on our website at <a href="http://www.thedinnerdaily.com">www.thedinnerdaily.com</a> or by going directly to <a href="http://app.thedinnerdaily.com">app.thedinnerdaily.com</a>&nbsp;The menus and shopping lists are posted on the site in accordance with <a href="/find-your-store/">the timetable listed on our website</a>.&nbsp; It is the subscriber’s responsibility to log into the site and retrieve the menu plans.&nbsp; As a courtesy, we also email out menu reports to our subscribers when menu plans are posted each week<strong>.&nbsp; </strong>Please note: access to the menu on the dashboard is considered as the primary delivery method of the menus, shopping list and coupons, not the email.</li>
<li>Nutritional information is provided using third party software&nbsp; and is to be used as approximate values only. T<strong>his information should NOT be used in making medical decisions.&nbsp;&nbsp;</strong>Nutritional values provided will vary from final results depending on actual measurements, products and the brand used to prepare the recipe.&nbsp;Unless otherwise noted on the recipe, the Service’s Family plan recipes make five (5) servings and the Meals for Two to Three recipes make two and a half (2.5) servings. Each subscriber should consult with his or&nbsp;her nutritionist or doctor as to individual dietary needs and/or restrictions as well as the appropriateness of any recipe. While the Service attempts to provide accurate nutritional and other data, the Service provides no warranty as to the accuracy of nutritional or other data.</li>
<li>The Dinner Daily Inc. will not be held liable for any adverse reactions due to the preparation and/or consumption of the recipes, whether related to allergies, medical conditions, or other causes.</li>
<li>By signing up for our service, you agree to allow us to send email to you with links to your weekly plans and from time to time with membership information or to let you know about new features. Since email services sometime incorrectly flag these emails as spam, The Dinner Daily makes no guarantees that subscribers will receive these email</li>
<li>Subscribers should print out the current week’s menu reports each week if they would like to keep a copy of the menu and shopping list.&nbsp; We only store the current week and previous week’s reports on the Member’s dashboard.&nbsp; Copies of prior menus or shopping list&nbsp;cannot be emailed out to subscribers.</li>
<li><strong>Refund Policy:&nbsp;</strong> There will be no charge if a subscriber cancels within the first 14 days.&nbsp; For cancellations after&nbsp;14 days,&nbsp;refunds&nbsp;will not be&nbsp;issued, but subscriptions will end at the end of the then current term.</li>
<li>All subscriptions will automatically be renewed and your account will be charged, unless you cancel before the renewal date.&nbsp; Subscribers&nbsp;may cancel their subscription by filling out the form on the “Account Settings” page.&nbsp; &nbsp; &nbsp;If you signed up for our service prior to Sept 2015 using your Paypal account, you should cancel by logging into your Paypal account or calling Paypal at 1-888-221-1161.&nbsp;&nbsp;&nbsp; If you have any problems cancelling your account please email us at <a href="mailto:support@thedinnerdaily.com">support@thedinnerdaily.com</a> and we will help you. &nbsp;<strong>Please note: unsubscribing to our mailing list DOES NOT cancel your account.</strong></li>
<li>The Dinner Daily Inc. is not affiliated with the grocery stores for which we provide menu plans. Our weekly menus are based on what is on sale at these stores, per the store’s advertised, publicly available sales. The grocery stores are responsible for the availability of the items on sale.&nbsp; Advertised sales items may vary from store to store and may not be available at all stores, or may be available at a different price from the advertised price, or may vary from store to store. The Dinner Daily makes no warranties that these items will be available.</li>
<li>The coupon search provided each week to subscribers is a supplemental service and although we work each week to identify helpful coupons, we do not guarantee that all coupons in circulation for items on the weekly shopping list will be identified on our lists.&nbsp; Coupons are also time sensitive and although the coupon may be available at the time of providing the link to subscribers, coupons can expire at any time as determined by the issuer of the coupon.</li>
<li>The Dinner Daily, Inc. may collect and store information about how you use the Service. Please refer to The Dinner Daily, Inc.’s&nbsp;<a href="/privacy-policy/">Privacy Policy</a> for information about how The Dinner Daily, Inc. collects, uses and discloses information about subscribers.&nbsp; Unless otherwise explained in the Privacy Policy, The Dinner Daily does not share or sell subscriber information.</li>
<li><strong>For weeks containing a major holiday, some menus may not be aligned with store sales depending on the store’s sales cycle and any changes the stores may make to their sales during holiday periods.</strong></li>
<li>The Dinner Daily, Inc. puts a lot of time and effort into creating valuable and interesting content (“Content”). Content includes any recipes, text, graphics, images, music, software, audio, video, works of authorship of any kind, and information or other materials that are posted, generated, provided or otherwise made available to you by way of The Dinner Daily, Inc.’s website and the Service. Content on The Dinner Daily, Inc’s website and any underlying code and technology are owned or licensed by The Dinner Daily, Inc. and are protected by copyright, trademark, patent, intellectual property, and other laws of the United States and foreign countries. In order to protect these rights, subscribers are prohibited from using, copying, removing, changing or obscuring any Content, copyright, trademark, service mark or other proprietary rights notices included in any Content (The Dinner Daily or otherwise) or posted on The Dinner Daily, Inc.’s website, except as expressly provided in these Terms and Conditions.&nbsp; All such rights and ownership are expressly reserved by The Dinner Daily.</li>
<li>References in the Service or on The Dinner Daily’s website to any other trademarks, products, services, processes or other information, by trade name, trademark, manufacturer, supplier or otherwise, does not constitute or imply endorsement, sponsorship or recommendation by The Dinner Daily, Inc.</li>
<li>The Dinner Daily, Inc.’s website may contain links to third party websites and resources (collectively “Third Party Websites”) that are not under The Dinner Daily, Inc.’s control. The Dinner Daily, Inc. provides these links only as a convenience and is not responsible for the content, products or services that are available from Third Party Websites. As such, a subscriber acknowledges sole responsibility and assumes all risk arising from his or her use of any Third Party Websites.</li>
<li>The Dinner Daily, Inc. does not grant to a subscriber any licenses or rights by implication or otherwise under any intellectual property rights owned or controlled by The Dinner Daily, Inc. or its licensors, except for the licenses and rights expressly granted in these Terms</li>
<li>Other than set forth herein, The Dinner Daily, Inc. is not obligated to monitor access or use of its website, Content or the Service, but The Dinner Daily, Inc. has the right to do so to facilitate the operation of the Service, to ensure compliance with these Terms, and to comply with applicable law or other legal requirements. The Dinner Daily, Inc. may consult with and disclose unlawful conduct to law enforcement authorities and pursuant to valid legal process, The Dinner Daily, Inc. may cooperate with law enforcement to prosecute users who violate the law. The Dinner Daily, Inc. reserves the right (but is not required) to remove or disable access to the Service, the website, and any Content at any time and without notice, and at The Dinner Daily’s sole discretion, if The Dinner Daily, Inc. determines that a subscriber’s use of the Service, the website or any Content is objectionable or in violation of these Terms or applicable law. The Dinner Daily, Inc. has the right to investigate violations of these Terms and any conduct that affects the Service, the website or the Content.</li>
<li>As a subscriber, you agree not to copy, reproduce, re-engineer or otherwise use any of the Content or software used or contained on <a href="http://www.thedinnerdaily.com">thedinnerdaily.com</a>.</li>
<li>If a subscriber breaches these Terms in any way, The Dinner Daily, Inc. may take such action as it deems appropriate to deal with the breach, including suspending access to the Service, prohibiting access to The Dinner Daily, Inc.’s website, blocking computers or mobile devices using a subscriber’s internet protocol (“IP”) address from accessing the Service, contacting a subscriber’s internet service provider to request that it block a subscriber’s access to the Service, bringing court proceedings against a subscriber, and/or any other rights or remedies that The Dinner Daily, Inc. may have under these Terms and Conditions.</li>
<li>A SUBSCRIBER IS SOLELY RESPONSIBLE FOR, AND ASSUMES ALL RISKS RELATED TO, THE PROPER AND SAFE WASHING, HANDLING, PREPARATION, STORAGE, COOKING, USE AND CONSUMPTION OF THE MEALS THAT A SUBSCRIBER MAKES BASED ON THE DINNER DAILY, INC.’S MENU PLANS. A SUBSCRIBER IS ALSO SOLELY RESPONSIBLE FOR KNOWING ABOUT ANY FOOD ALLERGIES AND VERIFYING THAT THE MENU PLANS ARE APPROPRIATE FOR USE.</li>
<li>THE DINNER DAILY, INC. ATTEMPTS TO DISPLAY CONTENT, INCLUDING PRICING AND NUTRITIONAL INFORMATION, AS ACCURATELY AS POSSIBLE. HOWEVER, THE DINNER DAILY, INC. DOES NOT GUARANTEE THE ACCURACY OF SUCH MATERIALS AND INFORMATION. THE RESULTS OF THE SERVICE MAY VARY FROM CONTENT DUE TO A NUMBER OF FACTORS, INCLUDING, WITHOUT LIMITATION, SYSTEM CAPABILITIES AND CONSTRAINTS OF A SUBSCRIBER’S COMPUTER, THE AVAILABILITY AND VARIABILITY OF COMPONENTS OF MENU PLANS, DISTINCT COOKING OR OTHER PREPARATION METHODS AND VARIABILITY OF COOKING EQUIPMENT AND APPLIANCES. THE SERVICE MAY CONTAIN INFORMATION ABOUT MENU PLANS AND WEEKLY STORE SPECIALS AND COUPONS THAT ARE NOT AVAILABLE IN EVERY LOCATION. A REFERENCE TO A MENU PLAN OR ITEM ON THE WEBSITE DOES NOT IMPLY OR GUARANTEE THAT IT IS OR WILL BE AVAILABLE IN A LOCATION.</li>
<li>EXCEPT AS EXPRESSLY SET FORTH IN THESE TERMS AND CONDITIONS, NEITHER THE SERVICE NOR THE DINNER DAILY, INC.&nbsp; MAKE ANY WARRANTIES, INCLUDING IMPLIED WARRANTIES, WITH RESPECT TO RECIPES AND THE NUTRITIONAL INFORMATION PROVIDED VIA THE SERVICE.&nbsp; &nbsp;ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT, ARE HEREBY DISCLAIMED BY THE SERVICE AND THE DINNER DAILY, INC.&nbsp; IN NO EVENT SHALL THE DINNER DAILY, INC. BE LIABLE FOR INDIRECT, INCIDENTAL, LIQUIDATED, OR CONSEQUENTIAL DAMAGES. WITHOUT LIMITATION TO THE FOREGOING, THE DINNER DAILY, INC. PROVIDES NO WARRANTY OR UNDERTAKING, AND MAKES NO REPRESENTATION OF ANY KIND THAT THE WEBSITE OR THE SERVICE WILL MEET A SUBSCRIBER’S REQUIREMENTS, ACHIEVE ANY INTENDED RESULTS, BE COMPATIBLE, BE ACCURATE, COMPLETE, RELIABLE, OR WORK WITH ANY OTHER WEBSITE, SYSTEMS, OR SERVICES, OPERATE WITHOUT INTERRUPTION, MEET ANY PERFORMANCE OR RELIABILITY STANDARDS OR BE ERROR-FREE, OR THAT ANY ERRORS OR DEFECTS CAN OR WILL BE CORRECTED.</li>
<li>TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL THE DINNER DAILY, INC. OR ITS AFFILIATES&nbsp; HAVE ANY LIABILITY ARISING FROM OR RELATED TO YOUR USE OF OR INABILITY TO USE THE SERVICE FOR: (a) PERSONAL INJURY, PROPERTY DAMAGE, LOST PROFITS, COST OF SUBSTITUTE GOODS OR SERVICES, LOSS OF DATA, LOSS OF GOODWILL, BUSINESS INTERRUPTION, COMPUTER FAILURE OR MALFUNCTION, OR ANY OTHER CONSEQUENTIAL, INCIDENTAL, INDIRECT, EXEMPLARY, SPECIAL, OR PUNITIVE DAMAGES; AND (b) DIRECT DAMAGES IN AMOUNTS THAT IN THE AGGREGATE EXCEED THE AMOUNT ACTUALLY PAID BY YOU FOR THE SERVICE.</li>
<li>Some jurisdictions do not allow the limitation or exclusion of liability for incidental or consequential damages, so the above limitation or exclusion may not apply to all subscribers.</li>
<li>These terms and conditions are subject to change from time to time without prior notice to subscribers.</li>
<li>By subscribing to, accessing and using the Service, a subscriber agrees to these Terms and Conditions and The Dinner Daily, Inc.’s Privacy Policy. If a subscriber disagrees with these Terms and Conditions or Privacy Policy or any part of either document, he or she must not subscribe to, access or use the Service.</li>
<li>The Dinner Daily, Inc is not be responsible for any failure or delay in performance under these Terms due to causes beyond its reasonable control, including, but not limited to, labor disputes, strikes, lockouts, shortages of or inability to obtain energy, raw materials or supplies, war, terrorism, riot, or acts of God.</li>
<li>These Terms and the resolution of disputes will be governed by and construed in accordance with the laws of the Commonwealth of Massachusetts without regard to its conflict of laws principles.</li>
<li>A subscriber may only resolve disputes with the Dinner Daily, Inc. on an individual basis as set forth below, and may not bring a claim as a plaintiff or a class member in a class, consolidated, or representative action. Class arbitrations, class actions, private attorney general actions, and consolidation with other arbitrations are not allowed under these Terms and Conditions.</li>
<li>No waiver by The Dinner Daily, Inc. of any provision set forth in these Terms and Conditions shall be deemed a continuing waiver of such provision or a waiver of any other provision, and any failure of The Dinner Daily, Inc. to assert a right or provision under these Terms and Conditions shall not constitute a waiver of such right or provision. If any provision in these Terms and Conditions is held by a court or other tribunal of competent jurisdiction to be invalid, illegal, or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent such that the remaining provisions of the Terms and Conditions will continue in full force and effect.</li>
<li>In the event that a subscriber has an issue with the Service, please send an email to info@thedinnerdaily.com.&nbsp; In the event that the issue cannot be resolved, any judicial proceeding will be brought in the federal or state courts of Suffolk County, Massachusetts. Subscribers consent to venue and personal jurisdiction there, and agree to waive rights to a jury trial.</li>
<li>Regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to a subscriber’s use of the Service must be filed within one (1) year after such claim or cause of action arose, or else that claim or cause of action will be barred forever.</li>
<li>Notwithstanding the foregoing, in the event of any unauthorized access to or use of the Service or Content in violation of these Terms and Conditions, The Dinner Daily, Inc. is entitled to apply for injunctive remedies (or an equivalent type of urgent legal relief) in any jurisdiction.</li>
<li>The Dinner Daily, Inc. may change or discontinue, temporarily or permanently, any feature or component of the Service, including these Terms and Conditions, at any time without notice. The Dinner Daily, Inc. is not liable to a subscriber for any modification, suspension or discontinuance of any feature or component of the Service, and reserves the right to determine the timing and content of any updates, which may be automatically downloaded and installed in connection with the Service without prior notice.</li>
</ul>`

module.exports  = {
    term_condition,
    privacy_policy
}